# Generated by Django 2.1.15 on 2020-04-28 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0005_board_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='dislike_users',
            field=models.ManyToManyField(related_name='dislike_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
